using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace CQEditorTools
{
    /// <summary>
    /// 代码生成器：将勾选的组件字段写入 {ClassName}.Components.cs partial 文件，
    /// 并在主脚本不含 partial 时自动补全关键字。
    /// </summary>
    public static class ExtractUIComponentCodeWriter
    {
        private const string AutoStart = "// <auto-generated-components>";
        private const string AutoEnd   = "// </auto-generated-components>";

        /// <summary>
        /// 执行代码写入。
        /// </summary>
        /// <param name="formComponent">UIForm 根组件，用于定位主脚本。</param>
        /// <param name="fields">用户最终勾选的字段条目（来自预览窗口）。</param>
        /// <param name="errorMessage">失败原因（成功时为 null）。</param>
        /// <returns>写入成功返回 true。</returns>
        public static bool Execute(
            Component               formComponent,
            List<ComponentFieldEntry> fields,
            out string              errorMessage)        {
            errorMessage = null;

            // ── 1. 定位主脚本 ─────────────────────────────────────────────────
            if (!TryFindMainScript(formComponent, out var mainScriptPath, out errorMessage))
                return false;

            var className  = formComponent.GetType().Name;
            var scriptDir  = Path.GetDirectoryName(mainScriptPath)!.Replace('\\', '/');
            var compPath   = $"{scriptDir}/{className}.Components.cs";

            // ── 2. 提取主脚本命名空间 ─────────────────────────────────────────
            var mainContent = File.ReadAllText(mainScriptPath);
            var namespaceName = ExtractNamespace(mainContent);

            // ── 3. 收集 using 指令 ────────────────────────────────────────────
            var usings = CollectUsings(fields);

            // ── 4. 生成 Components.cs 内容 ───────────────────────────────────
            var newline    = mainContent.Contains("\r\n") ? "\r\n" : "\n";
            var compContent = BuildComponentsFile(className, namespaceName, usings, fields, newline);

            // ── 5. 写入 Components.cs ─────────────────────────────────────────
            File.WriteAllText(compPath, compContent, Encoding.UTF8);

            // ── 6. 确保主脚本包含 partial 关键字 ─────────────────────────────
            if (!EnsurePartialKeyword(mainScriptPath, className, ref mainContent, newline,
                    out errorMessage))
                return false;

            // ── 7. 存储绑定任务（编译后自动应用）────────────────────────────
            var prefabAssetPath = AssetDatabase.GetAssetPath(formComponent.gameObject);
            ExtractUIComponentBindingApplier.StorePendingBindings(
                prefabAssetPath,
                formComponent.GetType().AssemblyQualifiedName,
                fields);

            AssetDatabase.Refresh();
            return true;
        }

        // ── 工具方法 ──────────────────────────────────────────────────────────

        /// <summary>通过 MonoScript 反射定位主脚本绝对路径（Assets 相对路径转全路径）。</summary>
        private static bool TryFindMainScript(Component comp, out string fullPath, out string error)
        {
            fullPath = null;
            error    = null;

            MonoScript script = null;
            if (comp is MonoBehaviour mb)
                script = MonoScript.FromMonoBehaviour(mb);

            if (script == null)
            {
                error = $"无法通过 MonoScript 定位 {comp.GetType().Name} 的脚本文件，" +
                        "请确保该组件脚本存在且已编译。";
                return false;
            }

            var assetPath = AssetDatabase.GetAssetPath(script);
            if (string.IsNullOrEmpty(assetPath))
            {
                error = "无法获取脚本资产路径。";
                return false;
            }

            fullPath = Path.Combine(Directory.GetCurrentDirectory(), assetPath)
                           .Replace('\\', '/');

            if (!File.Exists(fullPath))
            {
                error = $"脚本文件不存在：{fullPath}";
                return false;
            }

            return true;
        }

        /// <summary>从脚本内容中提取 namespace 名称；无 namespace 时返回 null。</summary>
        private static string ExtractNamespace(string content)
        {
            var m = Regex.Match(content, @"\bnamespace\s+([\w.]+)");
            return m.Success ? m.Groups[1].Value : null;
        }

        /// <summary>
        /// 收集所有字段类型的命名空间，排重后排序（System → UnityEngine → 其他）。
        /// </summary>
        private static List<string> CollectUsings(List<ComponentFieldEntry> fields)
        {
            var set = new HashSet<string>();
            foreach (var f in fields)
            {
                var ns = f.ComponentType.Namespace;
                if (!string.IsNullOrEmpty(ns))
                    set.Add(ns);
            }

            return set
                .OrderBy(ns =>
                {
                    if (ns.StartsWith("System"))          return 0;
                    if (ns.StartsWith("UnityEngine"))     return 1;
                    if (ns.StartsWith("UnityEditor"))     return 2;
                    return 3;
                })
                .ThenBy(ns => ns)
                .ToList();
        }

        /// <summary>生成完整的 .Components.cs 文件内容。</summary>
        private static string BuildComponentsFile(
            string                  className,
            string                  namespaceName,
            List<string>            usings,
            List<ComponentFieldEntry> fields,
            string                  nl)
        {
            var sb = new StringBuilder();

            // 文件头注释
            sb.Append("// 此文件由 ExtractUIComponent 工具自动生成，请勿手动修改。").Append(nl);
            sb.Append(nl);

            // using 指令
            foreach (var ns in usings)
                sb.Append($"using {ns};").Append(nl);
            if (usings.Count > 0)
                sb.Append(nl);

            // 命名空间包裹（无 namespace 则不缩进）
            bool hasNs    = !string.IsNullOrEmpty(namespaceName);
            string indent = hasNs ? "    " : string.Empty;

            if (hasNs)
            {
                sb.Append($"namespace {namespaceName}").Append(nl);
                sb.Append("{").Append(nl);
            }

            sb.Append($"{indent}public partial class {className}").Append(nl);
            sb.Append($"{indent}{{").Append(nl);

            // 自动生成区域
            sb.Append($"{indent}    {AutoStart}").Append(nl);
            foreach (var f in fields)
                sb.Append($"{indent}    public {f.ComponentType.Name} {f.FieldName};").Append(nl);
            sb.Append($"{indent}    {AutoEnd}").Append(nl);

            sb.Append($"{indent}}}").Append(nl);

            if (hasNs)
                sb.Append("}").Append(nl);

            return sb.ToString();
        }

        /// <summary>
        /// 确保主脚本中目标类声明含有 partial 关键字。
        /// 若已含有则跳过；否则在 class 前插入 partial 并写回。
        /// </summary>
        private static bool EnsurePartialKeyword(
            string mainScriptPath,
            string className,
            ref string content,
            string nl,
            out string error)
        {
            error = null;

            // 已经有 partial class ClassName，无需修改
            if (Regex.IsMatch(content, @"\bpartial\s+class\s+" + Regex.Escape(className)))
                return true;

            // 在 "class ClassName" 前插入 partial（保留访问修饰符及其他关键字）
            var pattern     = @"(\bclass\b\s+" + Regex.Escape(className) + @"\b)";
            var replacement = "partial class " + className;
            var updated     = Regex.Replace(content, pattern, replacement);

            if (updated == content)
            {
                // 未找到类声明，说明脚本结构异常
                error = $"未在主脚本中找到 class {className} 的声明，请手动添加 partial 关键字。";
                return false;
            }

            File.WriteAllText(mainScriptPath, updated, Encoding.UTF8);
            content = updated;
            return true;
        }
    }

    /// <summary>组件字段条目：字段名、运行时类型、节点路径（供绑定步骤使用）。</summary>
    public sealed class ComponentFieldEntry
    {
        public string FieldName;
        public Type   ComponentType;
        public string NodePath;
        public string AssemblyQualifiedTypeName;
    }
}
