// 此文件由 ExtractUIComponent 工具自动生成，请勿手动修改。

using UnityEngine;
using UnityEngine.UI;

namespace ProjectUI
{
    public partial class UITestForm
    {
        // <auto-generated-components>
        public RectTransform RTrsQuality;
        public Image ImgQuality;
        public RectTransform RTrsIcon;
        public Image ImgIcon;
        public Button BtnIcon;
        // </auto-generated-components>
    }
}
